### ISSUE TITLE
Add float64 vecs

### ISSUE THREAD

**Issue by creikey** [treeform/bumpy#20]

**Comment by treeform** [comment]
Sorry I don't think float64 version is panned at the moment. We don't have a good use case for it. Most of our work is in vec32 and we don't want the extra confusion from float64 vectors. 

You can always just fork and replace every vector with a float64 version.

Feel free to re-open if you disagree.

**Comment by creikey** [comment]
@treeform I was thinking that nim had a generic float type, so you could just replace `float32` with `gfloat` and `Vec2` with `GVec[T]` then the types are inferred when you use the library, either that or some kind of compile time parameter you pass to the library from nimble, so at the top of bumpy.nim is like

```nim
when doublePrecision:
    type Number = float64
    type Vector2 = GVec2[float64]
else:
    type Number = float32
    type Vector2 = Vec2
```

But after looking across google for a bit and reading some of the manual I can't figure out how to do either of these things.

The reason I need double precision math for collision routines is you need a double precision physics simulation for a lot of games where the world gets very large, it lets you avoid the extra complexity of something like origin rebasing
