### ISSUE TITLE
Inside collisions.

### ISSUE THREAD

**Issue by hylix** [treeform/bumpy#23]
I would like to know about internal collisions, for example a circle being in a circle should not be overlapping.

![overlaps](https://user-images.githubusercontent.com/393336/213848281-366873fc-4523-45d6-9805-39441ac66877.png)

**Comment by treeform** [comment]
That is by design. All objects in boxie's case are filled and all collisions internal. If you are making a game or UI system you want don't want objects to go inside other objects.

**Comment by hylix** [comment]
I understand that in boxie all objects are filled and in this case it does not makes sense.
I dont know about UI use cases, but in a game avoiding objects going out of another totally makes sense.
The picture I posted earlier is my program, the red circle grows until it collides with the blue circle then it shrinks.

**Comment by treeform** [comment]
Sorry this is the way bumpy collisions are. If you want to collide with a ring, maybe created them out of segments? Then do segment to segment overlap?

**Comment by hylix** [comment]
The solution is simple for circles and I implemented it.  
I get that this this the way bumpy is and I won't go against that, I just think that bumpy would profit from having that feature. 
Anyways I won't be annoying you more than that, I know you are working on great projects and I don't want to take more of your time. 
Thanks for all your great contributions and have a good rest of your day.
